language: ruby
rvm:
  - 2.6.0
services:
  - postgresql
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  app: apartments-feed
  api_key:
    secure: FewA2MEYQo/W5FQcv651wJCGWIF6vTvI8+lqx5t3ddMjWjP3lTjIHW86egfRWTrrb56Lf4CFuddgJPI+Q0XUOjGEPaFbA4H7kAVU7OXrn7Hz7ZqenhXqyYtij9+qeiwkr7TuJWVTEFZnA/QS4lpkmVr7ptVLCzwqTufpH5DWGmbl2dnFktq92XUt2DDxiAzRdNhVNfkTar7CCPnHDHs9z69H68nKq0AjZvtskPQ819B8J9d1lFC0kdX7Rzfk6ClPsEpJnEe/D+L0tjbSgQ7DqA43y+9vl19XMo6HjNbTXgbsMA87JdHP60Q3z+8ynPc/2A+2NUK6KTU3/JOtfLVHrZ37dXZrQF65yku5WOXU7VGAypA3F8lB2zKoyWbYkeuuakrY1FdkZdBsUT4wF/HAStnp2RC6JEFBnyBYgf1o4pij3cFqVmXxqvpFHqiAXIWUMu07bEvWuIB54xDid3GAmVQ7WPzcdvuZ4dGnbyt5KFmq7QB/8TxAf6ZjQ/C1I3mRMUpKm6SD2I8zcmuRsiXOMon/xAM1s3JkPhJyvkbagxOHp/UYrV0B7GIaMAbVMhMm9Uw1Vsk3OFY/zDbWnguZ7eg/TVPa+Y93MU5NqO+wTfeRWBKwg1l4kbT/NGHj6S9zaaNOtmKDOmdlX9CvCt1LNsCs7G5a1FbQRLsLArBzWVI=
